// TodoApp-Angular/src/app/components/todo-list/todo-list.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoService } from '../../services/todo-service.service';

@Component({
  selector: 'app-todo-list',
  templateUrl: './todo-list.component.html',
  styleUrls: ['./todo-list.component.css']
})
export class TodoListComponent implements OnInit {
  
  data: any[] = []

  constructor(private todoService: TodoService) { 
  }

  ngOnInit() {
  
    this.todoService.getTodos().subscribe(
      (todos: any[] )=> {
        this.data = todos
      })
    
  }
}

<div>
  <h2 style="text-align: center">TODO-LIST</h2>
  <div>
      <app-todo-item *ngFor="let todo of data" [todo]="todo"></app-todo-item>
  </div>
  <div class="inside">
    <app-todo-actions></app-todo-actions>
  </div>
</div>

// TodoApp-Vue/src/components/TodoList.vue
<template>
    <div>
        <h2 style="text-align: center">TODO-LIST</h2>
        <hr>
        <div>
            <app-todo-item v-for="todo in todos" :todo="todo" :key="todo._id"></app-todo-item>
        </div>
        <div class="inside">
            <app-todo-actions></app-todo-actions>
        </div>
    </div>
</template>
<script>
    import TodoItem from './TodoItem.vue'
    import TodoAction from './TodoAction.vue'
    import TodoService from '../services/TodoService'
    export default {
        data: function (){
            return {
                todos: []
            }
        },
        components: {
            appTodoItem: TodoItem,
            appTodoActions: TodoAction
        },
        created: function () {
            TodoService.getTodos((res) => {                
                this.todos = res
            })
        }
    }
</script>
<style scoped>
    * {
        margin: 0px;
    }
    .inside {
        position: absolute;
        bottom: 2px;
    }
</style>
