// TodoApp-Vue/src/components/AddTodo.vue
<template>
    <div>
    <h3 id="heading">Please input new todo</h3>
    <hr>
    <input type="text" id="txtInputTodo"  placeholder="Input Todo" v-model="todoTxt">
    <button type="submit" id="btnSubmit" @click="addTodo">ADD TODO</button>
    </div>
</template>
<script>
import TodoService from '../services/TodoService'
export default {
    data: function() {
        return {
            todoTxt: ''
        }
    },
    methods: {
        addTodo() {
            var todoTxt = this.todoTxt
            TodoService.addTodos(todoTxt, res => {
                console.log(res)
            })
        }
    }
}
</script>
<style scoped>
    #txtInputTodo {
        font-size: 20px;
        margin: 8px;
        width: stretch;
        display: block;
    }

    #btnSubmit {
        font-size: 20px;
        display: block;
        width: stretch;
        margin: 8px;
    }

    #heading {
        font-size: 20px;
        display: block;
        margin: 8px;
        text-align: center;
    }
</style>

// TodoApp-Angular/src/app/components/add-todo/add-todo.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { TodoService } from '../../services/todo-service.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  styleUrls: ['./add-todo.component.css']
})
export class AddTodoComponent implements OnInit {
  todo: FormGroup;
  constructor(private todoService: TodoService,  private router: Router) { }

  ngOnInit() {
    this.todo = new FormGroup({
      txtTodo: new FormControl(null, [Validators.required])
    })
  }
  onTodoAdd() {
    var todo = { todoTxt:this.todo.value.txtTodo }
  
    this.todoService.addTodo(todo)
    .subscribe(
      (response) => {
        if(response.status === 200) {
          this.router.navigateByUrl('/')
        } else if(response.status === 404) {
          
        }  else {
         
        }
      },
      (error) => console.log(error)
    );
  }
}

<div>
  <h3 id="heading">Please input new todo</h3>
  <form [formGroup]="todo" (ngSubmit)="onTodoAdd()">
    <input type="text" id="txtInputTodo"  placeholder="Input Todo" formControlName="txtTodo">
    <button type="submit" id="btnSubmit">ADD TODO</button>
  </form>
</div>
