// TodoApp-Vue/src/components/TodoItem.vue
<template>
    <div class="todo-item">
        <div class="todo-txt" @click="changeStatus(todo._id)">
            <input type="checkbox" value="todo._id" :checked="todo.status">{{todo.todoTxt}}
        </div>
        <div class="del-btn-div">
            <button @click="removeTodo(todo._id)" class="del-btn">DEL</button>
        </div>
    </div>
</template>
<script>
import TodoService from '../services/TodoService'
export default {
    props:["todo"],
    methods: {
        changeStatus(id) {
            console.log('changeStatus', id)
            TodoService.updateTodos(id, res => {
                console.log(res)
            })
        },
        removeTodo(id) {
            TodoService.deleteTodos(id, res => {
                console.log(res)
            })

        }
    }
}
</script>
<style>
.todo-item{
    margin: 2px;
    padding: 2px;
    border: 1px solid slateblue;
}

.todo-item:hover{
    background-color: paleturquoise;
}

.todo-txt, .del-btn-div {
    display: inline;
}

.del-btn {
    position: absolute;
    right: 2px;
    margin-right: 4px;
    color: red;
}
</style>

// TodoApp-Angular/src/app/components/todo-list/todo-item/todo-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { TodoService } from '../../../services/todo-service.service';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.css']
})
export class TodoItemComponent implements OnInit {
  
  @Input() todo: any;
  btn = 'btn'
  list= 'list'
  constructor(private todoService: TodoService) { 
  }

  ngOnInit() {
    
  }
  
  changeStatus(id) {
    this.todoService.changeStatus(id)
  }

  removeTodo(id) {
    this.todoService.removeTodo(id)
    .subscribe(
      (response) => {
        if(response.status === 200) {
          console.log('Deleted ',id)
        } else if(response.status === 404) {
          
        }  else {
         
        }
      },
      (error) => console.log(error)
    );
  }
}

<div class="todo-item">
  <div class="todo-txt" (click)="changeStatus(todo._id)">
      <input type="checkbox" [value]="todo._id" [checked]="todo.status">{{todo.todoTxt}}
  </div>
  <div class="del-btn-div">
    <button (click)="removeTodo(todo._id)" class="del-btn">DEL</button>
  </div>
</div>
